output_path: null
model_version: finetuning.model.v4_5
model_path: null
region: chr2:60005424-61005424
cap_list:
  - HIC2
cell_type: check4hic2_anewPaper_single_sample
batch_size: 1
no_confidence: true
